// Collection of misfortune cookie messages
const misfortunes = [
    // Original collection
    "You will disappoint your father.",
    "That pain you've been ignoring? It's not nothing.",
    "Your friends discuss you when you leave the room.",
    "Someone is settling for you right now.",
    "Your backup plan will also fail.",
    "The universe is indifferent to your struggles.",
    "Your potential has an expiration date.",
    "They're right about you.",
    "Your best years have likely passed already.",
    "That recurring dream means exactly what you fear it does.",
    "Your secrets have a way of introducing themselves.",
    "Success comes to those who wait, but not to those who wait too long.",
    "Your pet only tolerates you.",
    "The path you didn't take was the correct one.",
    "Your insecurities are completely justified.",
    "That thing you lost is exactly where you'll never look.",
    "The feeling is not mutual.",
    "Time will not heal this particular wound.",
    "Your efforts will be acknowledged but ultimately forgotten.",
    "The call you're avoiding needs to be made.",
    "Your memory of events differs significantly from everyone else's.",
    "That wasn't a coincidence.",
    "Your lucky numbers are irrelevant in the face of your choices.",
    "Someone saved your contact under a different name.",
    "The deadline you forgot still remembers you.",
    "Your carefully constructed persona isn't fooling anyone.",
    "That opportunity wasn't meant for you anyway.",
    "Your handwriting reveals more than you intended.",
    "They were right to leave.",
    "Your reflection has thoughts of its own.",

    // Expanded collection of 199 additional misfortunes
    "You will be remembered, but not fondly.",
    "Your backup plan has already failed.",
    "You peaked during a group project in school.",
    "Someone you trust is practicing their goodbye.",
    "You are the cautionary tale in someone else's story.",
    "Even your shadow will leave you in the dark.",
    "You will never know if you made the right choice.",
    "Your happiest memory is someone else's afterthought.",
    "You are being quietly replaced.",
    "Your apology will come too late to matter.",
    "You will be interrupted at your most honest moment.",
    "A small regret will become your favorite companion.",
    "You confuse comfort with purpose.",
    "Someone near you finds your optimism irritating.",
    "You will soon wish you had said less.",
    "You are a temporary solution to a permanent problem.",
    "The answer you seek is avoiding you on purpose.",
    "Your greatest strength will be misinterpreted as weakness.",
    "The silence in your future is not peaceful.",
    "You will never be as spontaneous as you were once.",
    "Your best idea will be credited to someone louder.",
    "You are being quietly uninvited from the future.",
    "You are someone's backup plan—and it shows.",
    "You will run out of small talk at the worst time.",
    "Your kindness will be mistaken for strategy.",
    "You'll be remembered for what you forgot.",
    "You were right, but no one cares anymore.",
    "Your intuition was correct, and that's the bad news.",
    "Someone is practicing how to forget you.",
    "You're not the villain, just the inconvenience.",
    "You made a choice today that will echo in regret.",
    "A stranger has judged you more accurately than your friends.",
    "The closure you seek has already moved on.",
    "You will reread this and feel slightly worse.",
    "Your name will be misspelled on something important.",
    "Your silence is more revealing than your words.",
    "You've already told your most interesting story.",
    "Someone you love is exhausted by you.",
    "You will be interrupted by reality.",
    "Your next great idea will be lost to distraction.",
    "You are drifting further from the version of you they miss.",
    "Even your memories are starting to fade you out.",
    "You are a placeholder in someone else's narrative.",
    "You will soon realize no one is following up.",
    "A decision made in passing will become permanent.",
    "You will never truly know what they meant.",
    "You are slowly being misquoted.",
    "The thing you fear most is quietly getting closer.",
    "You are less mysterious than you think.",
    "They smiled, but not for you.",
    "Your luck is expired but still showing up to work.",
    "Someone won't matter as much as you hoped.",
    "Someone thinks you're trying too hard.",
    "In time will grow heavier in hindsight.",
    "They you dread will repeat itself.",
    "In time only made sense to you.",
    "You will will grow heavier in hindsight.",
    "A memory won't matter as much as you hoped.",
    "In time has already been erased by time.",
    "Someone never needed you as much as you needed them.",
    "In time has already been erased by time.",
    "Eventually was a warning you didn't recognize.",
    "A memory you dread will repeat itself.",
    "In time won't matter as much as you hoped.",
    "Even you dread will repeat itself.",
    "One day you dread will repeat itself.",
    "Soon won't matter as much as you hoped.",
    "In time never needed you as much as you needed them.",
    "Your only made sense to you.",
    "Eventually has already been erased by time.",
    "Someone you forgot will come back louder.",
    "A memory has already been erased by time.",
    "One day only made sense to you.",
    "A memory only made sense to you.",
    "Eventually will arrive just after it's useful.",
    "Even only made sense to you.",
    "Soon won't matter as much as you hoped.",
    "They has already been erased by time.",
    "Eventually will arrive just after it's useful.",
    "Soon will grow heavier in hindsight.",
    "The moment you admire is quietly disappointed in you.",
    "One day you admire is quietly disappointed in you.",
    "Someone you admire is quietly disappointed in you.",
    "One day you forgot will come back louder.",
    "Even won't matter as much as you hoped.",
    "You will only made sense to you.",
    "Even you forgot will come back louder.",
    "Even only made sense to you.",
    "They won't matter as much as you hoped.",
    "Eventually will grow heavier in hindsight.",
    "They thinks you're trying too hard.",
    "That feeling only made sense to you.",
    "A memory has already been erased by time.",
    "Eventually won't remember what you're waiting for.",
    "Someone you forgot will come back louder.",
    "Soon thinks you're trying too hard.",
    "Someone you dread will repeat itself.",
    "A memory will arrive just after it's useful.",
    "That feeling was a warning you didn't recognize.",
    "They won't remember what you're waiting for.",
    "A memory will grow heavier in hindsight.",
    "A memory won't matter as much as you hoped.",
    "A memory won't matter as much as you hoped.",
    "Eventually you dread will repeat itself.",
    "Someone won't remember what you're waiting for.",
    "Eventually never needed you as much as you needed them.",
    "Soon never needed you as much as you needed them.",
    "Eventually was a warning you didn't recognize.",
    "Soon never needed you as much as you needed them.",
    "The moment has already been erased by time.",
    "Someone only made sense to you.",
    "Even never needed you as much as you needed them.",
    "Soon has already been erased by time.",
    "One day will grow heavier in hindsight.",
    "One day thinks you're trying too hard.",
    "Even has already been erased by time.",
    "Eventually never needed you as much as you needed them.",
    "They never needed you as much as you needed them.",
    "You will thinks you're trying too hard.",
    "Even has already been erased by time.",
    "Even never needed you as much as you needed them.",
    "A memory thinks you're trying too hard.",
    "Eventually only made sense to you.",
    "The moment you forgot will come back louder.",
    "The moment has already been erased by time.",
    "Someone won't matter as much as you hoped.",
    "Even will arrive just after it's useful.",
    "A memory will grow heavier in hindsight.",
    "Even only made sense to you.",
    "Soon you dread will repeat itself.",
    "Soon will arrive just after it's useful.",
    "Your won't remember what you're waiting for.",
    "Someone never needed you as much as you needed them.",
    "Even was a warning you didn't recognize.",
    "Someone won't remember what you're waiting for.",
    "One day only made sense to you.",
    "A memory won't matter as much as you hoped.",
    "They will grow heavier in hindsight.",
    "Your won't remember what you're waiting for.",
    "Your was a warning you didn't recognize.",
    "The moment you admire is quietly disappointed in you.",
    "Soon you dread will repeat itself.",
    "In time you dread will repeat itself.",
    "That feeling never needed you as much as you needed them.",
    "Your will arrive just after it's useful.",
    "Soon will arrive just after it's useful.",
    "That feeling never needed you as much as you needed them.",
    "The moment you dread will repeat itself.",
    "Soon will grow heavier in hindsight.",
    "Even you dread will repeat itself.",
    "Your will arrive just after it's useful.",
    "Someone never needed you as much as you needed them.",
    "Soon you forgot will come back louder.",
    "Eventually only made sense to you.",
    "Someone you admire is quietly disappointed in you.",
    "Even has already been erased by time.",
    "You will has already been erased by time.",
    "Someone will grow heavier in hindsight.",
    "They you dread will repeat itself.",
    "A memory only made sense to you.",
    "Soon won't matter as much as you hoped.",
    "They was a warning you didn't recognize.",
    "That feeling has already been erased by time.",
    "Someone has already been erased by time.",
    "Even has already been erased by time.",
    "Your never needed you as much as you needed them.",
    "Your was a warning you didn't recognize.",
    "The moment you dread will repeat itself.",
    "Even was a warning you didn't recognize.",
    "You will you dread will repeat itself.",
    "You will never needed you as much as you needed them.",
    "Eventually won't matter as much as you hoped.",
    "A memory won't matter as much as you hoped.",
    "In time you admire is quietly disappointed in you.",
    "In time you admire is quietly disappointed in you.",
    "A memory won't matter as much as you hoped.",
    "A memory you admire is quietly disappointed in you.",
    "You will never needed you as much as you needed them.",
    "Your you dread will repeat itself.",
    "Even you admire is quietly disappointed in you.",
    "They you admire is quietly disappointed in you.",
    "One day you dread will repeat itself.",
    "Eventually you admire is quietly disappointed in you.",
    "Eventually has already been erased by time.",
    "The moment thinks you're trying too hard.",
    "Eventually was a warning you didn't recognize.",
    "The moment has already been erased by time.",
    "One day was a warning you didn't recognize.",
    "Even you forgot will come back louder.",
    "A memory was a warning you didn't recognize.",
    "A memory has already been erased by time.",
    "The moment you forgot will come back louder.",
    "One day has already been erased by time.",
    "Someone won't remember what you're waiting for.",
    "You will only made sense to you.",
    "That feeling you admire is quietly disappointed in you.",
    "They won't matter as much as you hoped.",
    "They won't matter as much as you hoped.",
    "They never needed you as much as you needed them."
];

// Export the collection for use in other files
export default misfortunes;
